### ISSUE TITLE
Login command does not work

### ISSUE THREAD

**Issue by axsddlr** [cryptic20/valorant-discord#1]
!login <username> <password> does not work

**Comment by sherwyco** [comment]
it seems riots auth api has changed a bit. will have a look soon.

**Comment by sherwyco** [comment]
changing redirect uri ```    data = {
        'client_id': 'play-valorant-web-prod',
        'nonce': '1',
        'redirect_uri': 'https://beta.playvalorant.com/opt_in',
        'response_type': 'token id_token',
    }``` from ```https://beta.playvalorant.com/opt_in``` to ```https://playvalorant.com/opt_in``` solves the problem

**Comment by axsddlr** [comment]
`-login username password ` does not work, bot keeps asking for login after input creds then try `-rank` command

**Comment by sherwyco** [comment]
@Rehkloos hi, make sure you have the latest version. I just recently updated it. make sure your `DATABASE_URL` is also set properly. You would need mongodb installed on your system then your `.env` file would look something like this 
```
DATABASE_URL=mongodb://localhost/users
DISCORD_TOKEN=<your_discord_token>
DISCORD_PREFIX=-
DOMAIN_URL=http://localhost:3000
```
